register:
  path: /register
  controller: App\User\UserInterface\Controller\Security\RegisterController::index
  methods: POST

login:
  path: /login
  controller: App\User\UserInterface\Controller\Security\SecurityController::index
  methods: POST
