framework:
    messenger:
        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands: ~
            messenger.bus.events:
                default_middleware: allow_no_handlers
            messenger.bus.notifications: ~
            messenger.bus.queries: ~
