security:
    enable_authenticator_manager: true
    providers:
        user_provider:
            id: 'App\User\Infrastructure\SymfonyIntegration\Security\UserProvider'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/v1/
            lazy: true
            custom_authenticators:
                - App\User\Infrastructure\SymfonyIntegration\Security\ApiAuthenticator

    access_control:
        - { path: ^/api/v1/auth/(security|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/employer/offer/add, roles: ROLE_USER }
