security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/v1/
            custom_authenticators:
                - App\User\Infrastructure\SymfonyIntegration\Security\ApiKeyAuthenticator

    access_control:
        - { path: ^/api/v1/auth/(security|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
