version: '3.4'

services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
      target: api
    container_name: web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=UpPDG
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
